import sqlite3
conn = sqlite3.connect('database.db')
cursor = conn.cursor()

cursor.execute('INSERT INTO cast (nome) VALUES ("Park Gyu Young")')
cursor.execute('INSERT INTO cast (nome) VALUES ("Kang Min Hyuk")')
cursor.execute('INSERT INTO cast (nome) VALUES ("Park Seo Joon")')
cursor.execute('INSERT INTO cast (nome) VALUES ("Kim Da Mi")')
cursor.execute('INSERT INTO cast (nome) VALUES ("Gong Yoo")')
cursor.execute('INSERT INTO cast (nome) VALUES ("Kim Go Eun")')
cursor.execute('INSERT INTO cast (nome) VALUES ("Hyun Bin")')
cursor.execute('INSERT INTO cast (nome) VALUES ("Son Ye Jin")')
cursor.execute('INSERT INTO cast (nome) VALUES ("Song Joong Ki")')
cursor.execute('INSERT INTO cast (nome) VALUES ("Song Hye Kyo")')
cursor.execute('INSERT INTO cast (nome) VALUES ("Jeon Yeo Been")')
cursor.execute('INSERT INTO cast (nome) VALUES ("Ok Taec Yeon")')
cursor.execute('INSERT INTO cast (nome) VALUES ("Kim Soo Hyun")')
cursor.execute('INSERT INTO cast (nome) VALUES ("Jun Ji Hyun")')
cursor.execute('INSERT INTO cast (nome) VALUES ("Nam Joo Hyuk")')
cursor.execute('INSERT INTO cast (nome) VALUES ("Bae Suzy")')
cursor.execute('INSERT INTO cast (nome) VALUES ("Lee Min Ho")')
cursor.execute('INSERT INTO cast (nome) VALUES ("Park Shin Hye")')
cursor.execute('INSERT INTO cast (nome) VALUES ("Shin Min Ah")')
cursor.execute('INSERT INTO cast (nome) VALUES ("Kim Seon Ho")')

conn.commit()
conn.close()