import sqlite3
conn = sqlite3.connect('database.db')
cursor = conn.cursor()

cursor.execute('INSERT INTO genre (genre) VALUES ("Thriller")')
cursor.execute('INSERT INTO genre (genre) VALUES ("Drama")')
cursor.execute('INSERT INTO genre (genre) VALUES ("Drama")')
cursor.execute('INSERT INTO genre (genre) VALUES ("Romance")')
cursor.execute('INSERT INTO genre (genre) VALUES ("Fantasy")')
cursor.execute('INSERT INTO genre (genre) VALUES ("Romance")')
cursor.execute('INSERT INTO genre (genre) VALUES ("Romance")')
cursor.execute('INSERT INTO genre (genre) VALUES ("Drama")')
cursor.execute('INSERT INTO genre (genre) VALUES ("Action")')
cursor.execute('INSERT INTO genre (genre) VALUES ("Romance")')
cursor.execute('INSERT INTO genre (genre) VALUES ("Romance")')
cursor.execute('INSERT INTO genre (genre) VALUES ("Crime")')
cursor.execute('INSERT INTO genre (genre) VALUES ("Romance")')
cursor.execute('INSERT INTO genre (genre) VALUES ("Sci-Fi")')
cursor.execute('INSERT INTO genre (genre) VALUES ("Romance")')
cursor.execute('INSERT INTO genre (genre) VALUES ("Drama")')
cursor.execute('INSERT INTO genre (genre) VALUES ("Romance")')
cursor.execute('INSERT INTO genre (genre) VALUES ("Drama")')
cursor.execute('INSERT INTO genre (genre) VALUES ("Romance")')
cursor.execute('INSERT INTO genre (genre) VALUES ("Comedy")')

conn.commit()
conn.close()